### ISSUE TITLE
Issue when executing intent

### ISSUE THREAD

**Issue by snusnuz** [actions-on-google/dialogflow-quotes-nodejs#1]
"code": 14,
      "message": "Webhook error (206)"

Sorry I have this error while executing the welcome intent.

Are there issues with V2 API? Please let me know

**Comment by wortwart** [comment]
I got an empty response from Dialogflow. Firebase recorded a fetch error:
`FetchError: request to https://raw.githubusercontent.com/actions-on-google/dialogflow-quotes-nodejs/master/quotes.json failed, reason: getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443`
The URL is 200 ok.

**Comment by findzaatar** [comment]
Can you include some of your fulfillment code and give more details?

**Comment by findzaatar** [comment]
@snusnuz Did you enable billing? Just tested the sample and no issues

**Comment by taycaldwell** [comment]
@snusnuz If you are still running into this issue, please reopen.
